### ISSUE TITLE
Compilation bug : missing folder

### ISSUE THREAD

**Issue by BennyBellier** [NoxFly/c-cpp-project-script#1]
When I try to compile with structure 1. the compilation fails because the folder corresponding to the folder containing the .c/.cpp and .h is missing in the build folder.
You just have to create the corresponding folder in the build folder and the compilation succeeds.
I hope that you will be able to correct this little bug quickly.

**Comment by NoxFly** [comment]
Hello,
Thanks for the bug report.
Can you provide me more details ?
- From a blank or bigger project ?
- Did you modified the folder configuration inside the script, or with default configuration ?
- Have you made some changes in the Makefile ?
- What is printed in the console when you run `./run.sh -v` ?
- Did you try to clear objects and compile again, with `./run.sh -v -f` ?
- Which version of the script are you using ?
- And so on...

**Comment by NoxFly** [comment]
With no reply after some times, this issue is closed.
Please re-open an issue with more details if you continue to encounter this problem.
